### ISSUE TITLE
Pin Patient to List - Service

### ISSUE THREAD

**Issue by dennisdunn** [WorldVax/FC-Connect#69]
This service will handle the _patient queue_, the list of people who the caregiver will be seeing. The service should be able to add a patient, remove a patient, and re-order (prioritize) patients.

### Implementation Notes
- [x] Add a "pin" function to the SearchService
- [x] Add an "unpin" function to the SearchService
- [x] Add a function to get the pined patients

### Acceptance Criteria
- [x] The pin/unpin/view pinned functionality operates as expected.

**Comment by ONUHWT** [comment]
Testing comments

**Comment by xagronaut** [comment]
I've added a wireframe from past designs for context. See further descriptions of the required view in Issue #61. This is roughly the view that the service will support.

![patient_list 1](https://cloud.githubusercontent.com/assets/1373511/19913616/a5d1a594-a07a-11e6-885c-e68038206245.png)

**Comment by dennisdunn** [comment]
The design changed while implementing this story, those changes have been reflected in the requirements and acceptance criteria.
