### ISSUE TITLE
Patient Profile Add Current Vaccination - Service

### ISSUE THREAD

**Issue by dennisdunn** [WorldVax/FC-Connect#72]
### Implementation Notes
- [ ] Add design document
- [ ] Create the vaccination service
### Acceptance Criteria
- [ ] Unit tests pass

**Comment by xagronaut** [comment]
This is obsolete because the saving of the Vaccination is already handled in PatientCtrl.js, which populates relevant fields and then saves the whole Patient via PatientService.js.
